### PR TITLE
Update Fernetex

### PR DESCRIPTION
**Pull request by doomspork**
Howdy @kennyp!  I saw #5 but more so than just looking to resolve warnings, we're running into issues with very outdated dependencies.  I'm not 100% finished, I'd like to run dialyzer and see if there's any specs that need to be cleaned up, but I'd love to get your thoughts.

### CODE REVIEW

**Comment by kennyp** [comment]
@doomspork I went ahead and merged #5 to get rid of the warnings, but I like where you're headed. I'm a big dialyzer fan so getting those straight would be awesome.

**Comment by doomspork** [comment]
@kennyp I will rebase on #5 and ping you when things are ready for a final look

**Comment by doomspork** [comment]
@kennyp let me know your thoughts.  I made a couple big changes:

+ Public API `generate/2` and `verify/2` return `{:ok, ...}` and `{:error, reason}` tuples
+ New `generate!/2` and `verify/2` return the result or raise an error.

@kennyp do you want to enforce an 80 character limit?  There's a few spots in the code that exceed that Credo would like us to resolve.  If you're happy exceeding 80, I'll update the credo config to something else (100, 120?).

**Comment by kennyp** [comment]
@doomspork I've always been an 80 char kind of guy, but given that all of the lines that violate that limit would look gnarly cutting them down I think bumping up to 100 would be totally fine. Thanks for the PR, it looks really good.

**Comment by doomspork** [comment]
Let me know if there's any changes you'd like to see @kennyp 😁

**Comment by kennyp** [comment]
@doomspork I'm going to go ahead and merge, and tag a release. Thanks.

**Comment by doomspork** [comment]
Thank you @kennyp!

**Pull request merged**
